CREATE DATABASE LearnSQL;

USE LearnSQL;

CREATE TABLE Stages
(
	Stage INT PRIMARY KEY,
	[Name] NVARCHAR(MAX) NOT NULL,
);

CREATE TABLE Users
(
	Username NVARCHAR(30) PRIMARY KEY,
	[Name] NVARCHAR(30) NOT NULL,
	Surname NVARCHAR(30) NOT NULL,
	[Password] NVARCHAR(30) NOT NULL,
	Stage INT FOREIGN KEY REFERENCES Stages(Stage)
);

CREATE TABLE Materials
(
	ID INT PRIMARY KEY,
	Theory TEXT NOT NULL,
	StageID INT REFERENCES Stages(Stage)
);

CREATE TABLE Excercise
(
	ID INT PRIMARY KEY,
	Problem NVARCHAR(MAX) NOT NULL,
	Solution NVARCHAR(MAX) NOT NULL
);

CREATE TABLE MaterialsExcercise
(
	MaterialID INT FOREIGN KEY REFERENCES Materials(ID),
	ExcerciseID INT FOREIGN KEY REFERENCES Excercise(ID)
);